anagram/urls.py
from django.urls import path

from . import views

app_name='anagram'
urlpatterns = [
    path('', views.index, name='index'),
    path('generate/', views.generate, name='generate'),
    path('<int:word_id>/list/', views.list, name='list'),
]

project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('anagram/', include('anagram.urls')),
]

anagram/models.py
from django.db import models

# Create your models here.
class Word(models.Model):
    wordText = models.CharField(max_length=200)
    def __str__(self):
        return self.wordText

class Anagram(models.Model):
    word = models.ForeignKey(Word, on_delete = models.CASCADE)
    anagramText = models.CharField(max_length=200)
    def __str__(self):
        return self.anagramText

anagram/views.py
import re
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import get_list_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django import forms

from anagram.models import Word
from anagram.models import Anagram
from anagram import logic

def index(request):
    return render(request, 'anagram/index.html')

# TODO: sanitize/clean input
def generate(request):
    if request.method == 'POST':
        form = forms.Form(request.POST)
        if form.is_valid():

            input = request.POST.get('userinput')
            oldWordList = Word.objects.filter(wordText=input.capitalize())

            # if word and anagrams have already been generated
            if oldWordList:
                oldWord = oldWordList[0]
                return HttpResponseRedirect(reverse('anagram:list', args=(oldWord.id,)))
            # if user inputs a new word
            anagrams = logic.webRequest(input)
            if anagrams != []:
                newWord = Word(wordText=input.capitalize())
                newWord.save()
                for anagram in anagrams:
                    newAnagram = Anagram(word=newWord, anagramText=anagram)
                    newAnagram.save()
                return HttpResponseRedirect(reverse('anagram:list', args=(newWord.id,)))
            
    else:
        form = forms.Form()
    return render(request, 'anagram/index.html', {'form' : form}) # TODO: make this prettier

def list(request, word_id):
    word = get_object_or_404(Word, pk=word_id)
    anagrams = get_list_or_404(Anagram, word=word_id)
    return render(request, 'anagram/list.html', {'word': word, 'anagrams': anagrams})

anagram/templates/anagram/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta chartset="utf-8">
        <title>Anagram</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'anagram/style.css' %}">
    </head>
    <body>
        <h1>Anagram Generator</h1>
        <form action="{% url 'anagram:generate' %}" method="post">
        {% csrf_token %}
        <textarea name="userinput" id="userinput" placeholder="Enter a word to generate anagrams..."></textarea>
        <div id="buttoncontainer">
            <input type="submit" value="Generate">
        </div>
        </form>
    </body>
</html>

anagram/templates/anagram/list.html
<!DOCTYPE html>
<html>
    <head>
        <meta chartset="utf-8">
        <title>Anagram</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'anagram/style.css' %}">
    </head>
    <body>
        <h1>Anagrams for word: {{ word.wordText }}</h1>
        <div class="box">
            <ul id="anagramList">
                {% for anagram in anagrams %}
                <li>
                    {{ anagram.anagramText }}
                </li></br>
                {% endfor %}
            </ul>
        </div>
        <div id="returnLink">
            <a href="{% url 'anagram:index' %}">Return</a>
        </div>
    </body>
</html>

anagram/templates/anagram/result.html
<!DOCTYPE html>
<html>
    <head>
        <meta chartset="utf-8">
        <title>Anagram</title>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'anagram/style.css' %}">
    </head>
    <body>
        <h1>Result page</h1>
        <ul>
            <div>juuh</div>
            <div>elikkäs</div>
        </ul>
    </body>
</html>